name: AIO AirbenCoder

on:
  workflow_dispatch:
    inputs:
      Season:
        description: "Season, 01/02/03"
        required: true
        type: number
      EpLabel:
        description: "EpLabel, E?? / E12E13/E19E20 / E10E11/E14E15/E18E19E20E21"
        required: true
        type: number
      SpeedProf:
        description: "SpeedProf"
        required: true
        default: "2x540"
        type: choice
        options:
        - "0x720"
        - "2x720"
        - "2x540"
        - "1x540"
      RoughQuality:
        description: "Lower Quality?"
        required: true
        type: boolean
        default: true
      QCReport:
        description: "QC Report?"
        required: true
        type: boolean
        default: false

env:
  SOURCERY: ${{ secrets.SOURCERY }}
  AniCode: "theLastAirbender"
  AniName: "Avatar.The.Last.Airbender"
  LocationOnIndex: "tdz5:/Avatar.The.Last.Airbender.BluRayRipZ"
  Season: ${{ github.event.inputs.Season }}
  EpLabel: ${{ github.event.inputs.EpLabel }}
  EpisodeLabel: "S${{ github.event.inputs.Season }}${{ github.event.inputs.EpLabel }}"
  SpeedProf: ${{ github.event.inputs.SpeedProf }}
  RoughQuality: ${{ github.event.inputs.RoughQuality }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}

jobs:
  primary:
    name: Prepare Steps for R3Encod3r
    runs-on: ubuntu-22.04

    outputs:
      EncSpeed: ${{ steps.set-params.outputs.EncSpeed }}
      R3NC0D3R: ${{ steps.set-params.outputs.R3NC0D3R }}
      VidRes: ${{ steps.set-params.outputs.VidRes }}
      JobPostfix: ${{ steps.set-params.outputs.JobPostfix }}
      matrix: ${{ steps.set-params.outputs.matrix }}
      safile_json: ${{ steps.set-params.outputs.safile_json }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "rtools"
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncSCR-efb6960f0cd2
      - name: Create EncMatrix
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./41-EncSCR-0b11655ee4f6
      - name: Export Parameters
        id: set-params
        run: |
          echo "EncSpeed=${EncSpeed}" >> $GITHUB_OUTPUT
          echo "R3NC0D3R=${R3NC0D3R}" >> $GITHUB_OUTPUT
          echo "VidRes=${VidRes}" >> $GITHUB_OUTPUT
          echo "JobPostfix=${JobPostfix}" >> $GITHUB_OUTPUT
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
          echo "safile_json=${safile_json}" >> $GITHUB_OUTPUT

  enc_reavatar:
    name: Encode Phase
    runs-on: ubuntu-22.04
    needs: primary

    strategy:
      fail-fast: false
      max-parallel: 18
      matrix:
        ChunkNum: ${{fromJson(needs.primary.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "ftools rtools"
          safile_json: ${{ needs.primary.outputs.safile_json }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncSCR-efb6960f0cd2
      - name: ${{env.R3NC0D3R}} R3NC0D3R - ${{env.EpisodeLabel}} - Chunk_${{env.ChunkNum}}
        env:
          ChunkNum: ${{ matrix.ChunkNum }}
          EncSpeed: ${{ needs.primary.outputs.EncSpeed }}
          R3NC0D3R: ${{ needs.primary.outputs.R3NC0D3R }}
          VidRes: ${{ needs.primary.outputs.VidRes }}
          JobPostfix: ${{ needs.primary.outputs.JobPostfix }}
          QCReport: ${{ github.event.inputs.QCReport }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./61-EncSCR-d1ff85e0f8a1

  postEnc:
    name: Merge Episode
    runs-on: ubuntu-22.04
    needs: [primary, enc_reavatar]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "ftools rtools"
          safile_json: ${{ needs.primary.outputs.safile_json }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncSCR-efb6960f0cd2
      - name: Merge ${{env.AniCode}} - ${{env.EpisodeLabel}}
        env:
          EncSpeed: ${{ needs.primary.outputs.EncSpeed }}
          R3NC0D3R: ${{ needs.primary.outputs.R3NC0D3R }}
          VidRes: ${{ needs.primary.outputs.VidRes }}
          JobPostfix: ${{ needs.primary.outputs.JobPostfix }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./91-EncSCR-ff51670f6795
